// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB63pqCEFKpwHdCaY2bvG88ATp2izfi2ko',
    appId: '1:435489751845:web:07df4b760c7567b87590cc',
    messagingSenderId: '435489751845',
    projectId: 'financialnote-a5b4c',
    authDomain: 'financialnote-a5b4c.firebaseapp.com',
    storageBucket: 'financialnote-a5b4c.firebasestorage.app',
    measurementId: 'G-MDEKFNZW53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD99o8qOmOJaN_G9tJyS_jouyzLTjNAiVg',
    appId: '1:435489751845:android:a28228eba0bbb2c87590cc',
    messagingSenderId: '435489751845',
    projectId: 'financialnote-a5b4c',
    storageBucket: 'financialnote-a5b4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmw1uJiQHoV0KOluy0Iuk6L1daPDc3GcM',
    appId: '1:435489751845:ios:5f75238311dda4397590cc',
    messagingSenderId: '435489751845',
    projectId: 'financialnote-a5b4c',
    storageBucket: 'financialnote-a5b4c.firebasestorage.app',
    iosBundleId: 'com.example.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmw1uJiQHoV0KOluy0Iuk6L1daPDc3GcM',
    appId: '1:435489751845:ios:5f75238311dda4397590cc',
    messagingSenderId: '435489751845',
    projectId: 'financialnote-a5b4c',
    storageBucket: 'financialnote-a5b4c.firebasestorage.app',
    iosBundleId: 'com.example.wallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB63pqCEFKpwHdCaY2bvG88ATp2izfi2ko',
    appId: '1:435489751845:web:c461eb89dfa882ca7590cc',
    messagingSenderId: '435489751845',
    projectId: 'financialnote-a5b4c',
    authDomain: 'financialnote-a5b4c.firebaseapp.com',
    storageBucket: 'financialnote-a5b4c.firebasestorage.app',
    measurementId: 'G-66XWM5R04T',
  );
}
